// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9EJXGIvnhLtAPdbcUvEIYRJ51gEhlnQ',
    appId: '1:602706781254:web:c81e8aa648e1a0f74b5647',
    messagingSenderId: '602706781254',
    projectId: 'chats-b3204',
    authDomain: 'chats-b3204.firebaseapp.com',
    databaseURL: 'https://chats-b3204-default-rtdb.firebaseio.com',
    storageBucket: 'chats-b3204.appspot.com',
    measurementId: 'G-9ZT0ME0ZYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATs-f46O5_l9wSrKsol2Xt6FC8s1Cdzz4',
    appId: '1:602706781254:android:3bce5949ef67fffe4b5647',
    messagingSenderId: '602706781254',
    projectId: 'chats-b3204',
    databaseURL: 'https://chats-b3204-default-rtdb.firebaseio.com',
    storageBucket: 'chats-b3204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPnTuv4H71TVmAvq1HTTogyqz-X4-c7w',
    appId: '1:602706781254:ios:f018ba598cb312104b5647',
    messagingSenderId: '602706781254',
    projectId: 'chats-b3204',
    databaseURL: 'https://chats-b3204-default-rtdb.firebaseio.com',
    storageBucket: 'chats-b3204.appspot.com',
    androidClientId: '602706781254-5nuh5sa9jqv043lg3a80rrflc38jpfcv.apps.googleusercontent.com',
    iosClientId: '602706781254-ij1nhph6b8q9voov8fechip3cm7fkc3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPPnTuv4H71TVmAvq1HTTogyqz-X4-c7w',
    appId: '1:602706781254:ios:f018ba598cb312104b5647',
    messagingSenderId: '602706781254',
    projectId: 'chats-b3204',
    databaseURL: 'https://chats-b3204-default-rtdb.firebaseio.com',
    storageBucket: 'chats-b3204.appspot.com',
    androidClientId: '602706781254-5nuh5sa9jqv043lg3a80rrflc38jpfcv.apps.googleusercontent.com',
    iosClientId: '602706781254-ij1nhph6b8q9voov8fechip3cm7fkc3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ0fjwXM_DH53JhEA0Pt_jqvIdOwidPks',
    appId: '1:602706781254:web:866f2c00624ef6524b5647',
    messagingSenderId: '602706781254',
    projectId: 'chats-b3204',
    authDomain: 'chats-b3204.firebaseapp.com',
    databaseURL: 'https://chats-b3204-default-rtdb.firebaseio.com',
    storageBucket: 'chats-b3204.appspot.com',
    measurementId: 'G-XLL395HPHQ',
  );
}
